- eval_test.go
The simple test case I added is failing and I'm wondering if I'm doing something completely outlandish here. Although this particular example is contrived I have a real need in a project of mine for this to work.
Can you take a look, please?
> Add failing test case for string comparison in if

- loader.go
- loaders/httpfs/loader.go
- loaders/multi/multi.go
- template.go
I got to play around with the new loaders you guys added in #48 and there are a few things that caught my eye while switching from my naive implementation (the one in #37).
Because we're always loading templates from the file system in development and only switch to a binary packaged `http.FileSystem` I needed to copy over your `osFileSystemLoader` implementation – it wasn't exported so I couldn't instantiate it myself. That made me write another custom loader to stitch that and the `httpfs` loader together. All in all I felt like this could be improved so here goes:
1. I made the `osFileSystemLoader` public so it can be used on its own and I didn't see any disadvantage in keeping this private to the library.
2. I added a simple multi loader implementation that is still a `jet.Loader` but …
> Improve custom loaders

- .travis.yml
This fixes #69 and follows the larger Go community's guidelines.
> Run TravisCI tests in Go 1.8 and 1.9

- eval_test.go
- lex.go
- lex_test.go
- parse.go
- testData/new_block_yield.jet
- testData/range.jet
This fixes #86 but isn't just for `yield`s but because the parser easily handles this as "inside-actions" it's now also possible when invoking functions and defining blocks.
As a quick example these would have failed with `unclosed action` before but work now:
```
{{block col(
columns,
)}}
…
{{yield row(
cols="12",
rowClass="highlight-row",
) content}}
{{replace("My Name Is II",
" ",
"_",
-1,
)}}
```
Edit: the edge case below is fixed.
I noticed one edge case:
```
{{replace("My Name Is II",
" ",
"_",
-1,
)}}
```
~Here the dangling comma after the -1 trips up the parser and it fails with `unexpected token ")" on operand` because it expects the decimal number to continue. One way to fix it is to disallow dangling commas (which are actually a side effect of the lexer) but that syntax feels …
> Implement multiline handling for yield/block/function definitions

- README.md
- appveyor.yml
- eval_test.go
- examples/asset_packaging/Makefile
- examples/asset_packaging/main.go
- examples/asset_packaging/views/includes/_partial.jet
- examples/asset_packaging/views/includes/blocks.jet
- examples/asset_packaging/views/index.jet
- jettest/test.go
- parse_test.go
I finally got around to adding AppVeyor for running the test suite on Windows in our PRs. It's especially related to #78. The good news is that Jet already works correctly on Windows. :+1: AppVeyor is free for open source projects.
I marked it as a work-in-progress because there's a few issues we still need to discuss:
> Run test suite on Windows via AppVeyor

- eval.go
- eval_test.go
For now I just added 2 failing test cases. Maybe this isn't just about string pointers but others like int pointers as well.
> Fix evaluating pointers

- eval.go
- eval_test.go
This pr fixes Jet Runtime error when accessing nil element of the `map[string]interface{}` via dot.
Should fix #101
> WIP: Fix different behaviour when accessing maps

- lex.go
- lex_test.go
- parse.go
- parse_test.go
- template.go
- testData/custom_delimiters.jet
This fixes #68 and introduces the ability to use custom delimiters.
Use like this:
```go
var View = jet.NewHTMLSet("./views"))
View.Delims("[[", "]]")
```
```html
[[ extends "layouts/application.jet" ]]
[[ block body() ]]
<main>
This content will be yielded in the layout above.
</main>
[[ end ]]
```
TODO:
This fixes #68 and closes #98.
> Add ability to use custom delimiters

- default.go
- eval.go
- eval_test.go
Previously, the key/index and element values returned by Ranger were reflect.Values pointing to the underlying data (see https://golang.org/src/reflect/value.go?s=67137:67170#L2242 and https://golang.org/src/reflect/value.go#L140). This meant you could not compare e.g. elements of a string slice to a string literal. Also, storing a copy of a certain slice element's index and using it outside of the range did not work, since the copy only pointed to the actual index (which had the value len+1 after the range).
> make Ranger return interface{}, not reflect.Value

- eval.go
- eval_test.go
- func.go
- go.mod
- go.sum
- node.go
Sorry for the big PR, but this was the easiest way to clean up the mess I created with the last PR :D
- make `Ranger` return `reflect.Values` again (see https://github.com/CloudyKit/jet/issues/122#issuecomment-572311118)
- fix #117 (using fix from https://github.com/CloudyKit/jet/issues/117#issuecomment-518576462)
- fix #122 (@tooolbox: check out https://github.com/sauerbraten/jet-example/tree/v2.1.3-6d666f94dfe7)
- fix #123 (@tooolbox: check out https://github.com/sauerbraten/jet-example/tree/v2.1.3-91ac9cb)
- move pointer dereferencing to fastprinter package (see https://github.com/CloudyKit/jet/pull/125#issuecomment-572555115, https://github.com/CloudyKit/fastprinter/pull/2)
- add `IsSet` function to `*Arguments` type
This PR obsoletes #125.
> Misc fixes related to Ranger and pointer evaluation/printing

- .travis.yml
- template.go
- template_test.go
- Add go 1.14(.travis.yml).
- Exposing a method for modifying `Set.defaultExtensions`.
> Add Set.SetExtensions to specify set's extensions

- eval.go
Previously, when Jet encountered a `yield` statement that's missing a parameter name like `{{yield foo(p)}}` it would panic because of a null pointer. This change will detect the missing name and throw an error instead.
Closes #133
> Don't panic when parameter name in yield is missing

- default.go
- eval.go
A pointer (or interface value that does not implement the Ranger type) would be treated like a slice or array, regardless of the underlying value's kind.
`fallthrough` jumps to the next case block without verifying the case condition, which is not what we want in the case of indirection.
> fix fallthrough bug in getRanger 

- eval.go
- eval_test.go
Previously, code like
```
{{ bla := map() }}
{{ if isset(bla.foo[0].bar)}}
true
{{else}}
false
{{end}}
```
would produce a panic, because `bla.foo[0].bar` is parsed as a chain node consisting of `bla.foo[0]` as base and `.bar` as the single field. evalChainNodeExpression() then evaluated `bla.foo[0]` as an index expression using evalPrimaryExpressionGroup(), which would result in a panic.
This change recovers from all panics happening during the evaluation of the argument to isset().
(The duplication of logic between isSet() and evalPrimaryExpressionGroup() is a continued source of bugs and inconsitencies and I'd like to try and get rid of it in the long term by making isSet() a simple wrapper around evalPrimaryExpressionGroup() with the recover code from this change.)
> recover from panics that happen when evaluating an expression inside isset()

- constructors.go
- default.go
- eval.go
- eval_test.go
- jettest/test.go
- loader.go
- loaders/httpfs/httpfs_test.go
- loaders/httpfs/loader.go
- loaders/multi/multi.go
- loaders/multi/multi_test.go
- node.go
- parse.go
- template.go
- utils/visitor_test.go
This fixes #127 (paths in templates will be handled as described there) and #128.
Breaking changes:
- `OSFileSystemLoader` only supports a single directory instead of multiple
- the `AddPath` and `AddGopathPath` functions were removed
- ~~`Loader.Exists` no longer returns the "real" file name~~
- after `include` or `extends`, relative paths will no longer be looked up as absolute paths (see #127)
I removed the ability to have multiple directories managed by a single `OSFileSystemLoader` becaue of #128, and because I feel like
1. most users will have all templates in a single directory, organized into subdirectories there,
2. with the new handling of relative paths, the top directory name will appear in paths less often, and
3. you can always use `loaders.Multi` to get back the …
> Clean up template loading

- default.go
- eval.go
- eval_test.go
- ranger.go
Basically, if the ranger provides both a range value and index, the one-var syntax sets that var to the index. If the ranger provides no index, one-var syntax will give you the value.
This way, Jet's range now behaves like Go's range for maps, slices, arrays, and channels.
Closes #158.
> Assign the range key/index in one-var syntax with rangers that provide an index

- examples/todos/main.go
`todos` example: Add `ProvidesIndex() bool` method to `doneTODOs` in order to complete the new `jet.Ranger` interface, which now contains two methods, the `Range` and the new `ProvidesIndex`.
/ping @razonyang
> Add ProvidesIndex() bool to complete the new jet.Ranger interface

- constructors.go
- docs/changes.md
- docs/syntax.md
- eval.go
- eval_test.go
- lex.go
- lex_test.go
- node.go
- parse.go
- testData/assignment.jet
This adds Go-like handling of `_` in assignments, skipping creating or updating a variable reference but still evaluating the corresponding right side of the assignment. The updated docs explain it well:
> Assigning anything to `_` tells Jet to evalute the right side, but skip the actual assignment to a new or existing identifier. This is useful to call a function but discard its return value:
>     {{ _ := stillRuns() }}
>     {{ _ = stillRuns() }}
> Since no actual assigning takes place, both of the above are equivalent: `stillRuns` is executed, but the return value will neither be stored in a variable, nor will it be rendered (unlike `{{ stillRuns() }}`, which would render the return value to the output).
> detect '_' as special discard syntax in assignments

- eval.go
- eval_test.go
- jettest/test.go
- loader.go
- loaders/httpfs/httpfs_test.go
- loaders/multi/multi_test.go
- node.go
- parse.go
- parse_test.go
- template.go
- template_test.go
- utils/visitor_test.go
~~Keeping track of wether or not to cache templates that are imported/extended during Parse() is too much work, so Parse() is gone for now.~~ LoadTemplate() is removed in favor of a new in-memory Loader where you can add templates on-the-fly (which is also used for tests without template files). Using it together with a file loader via a multi loader restores the previous functionality.
I believe this fixes #180.
> cache more aggressively; remove Set.LoadTemplate()

- eval.go
- eval_test.go
- ranger.go
Depends on #200
This improves the performance of resolveIndex calls by bringing back the structure cache access that was removed in commit https://github.com/CloudyKit/jet/commit/be876debf33e1e830c07cba38d2a592b0a7b2807 and by modifying the function's signature to receive either a reflect.Value or a string argument, depending on what the call sites already have. This brings down allocations for the most common execution paths back to zero.
Benchmarks shows that the hot path for executing templates involve allocations made when executing a {{ .Field }} action when the current context is a structure. This is one of the most fundamental building blocks for templates, and thus deserves a closer inspection on how to make performant.
Going over the history of this package, up to version 3.0.0, …
> eval: resolveIndex speedup

- default.go
- docs/syntax.md
- eval_test.go
- ranger.go
- ranger_test.go
This uses an indirection trick to avoid an allocation in intsRanger.Range call, signficantly improving its performance during iteration.
The trick involves calling reflect.ValueOf on the address of the field instead of using its concrete value. This avoids an allocation performed by the Go runtime to convert the int value to an interface value.
In order to use this trick, the interpretation of the 'i' field needed to be changed from "next index" to "previous index" and its initialization needed to be offset by -1.
Following is the impact of this change in the relevant benchmark:
```
name          old time/op    new time/op    delta
IntsRanger-4    61.0ns ± 2%    23.1ns ± 1%   -62.12%  (p=0.000 n=10+9)
name          old alloc/op   new alloc/op   delta
IntsRanger-4     15.0B ± 0%      0.0B …
```
> ranger: Improve intsRanger performance

- examples/asset_packaging/main.go
- examples/todos/main.go
- set.go
Allowing DevelopmentMode to be set on or off via a variable is a common pattern I missed.
> Allow DevelopmentMode to be set on or off.

- eval.go
- eval_test.go
- ranger_test.go
The regression was introduced in 3838f8b1234c7dd32a42bf3ec55d79f426deb03e as part of the struct field caching.
As a bonus, I found and fixed another bug in that same commit that allowed accessing unexported struct fields from templates.
Fixes #220.
> fix ranger empty interface regression

- README.md
beta.pkg.go.dev requires a login
> Update link for Go API to point to pkg.go.dev instead of beta.pkg.go.dev
